version: '3.8'

services:
  postgres:
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - g:/cache/zoomcamp/db:/var/lib/postgresql/data

  scheduler:
    build: .
    command: scheduler
    depends_on:
      - postgres
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - g:/cache/zoomcamp/logs:/opt/airflow/logs

  webserver:
    build: .
    depends_on:
      - postgres
      - scheduler
    entrypoint: ./scripts/entrypoint.sh
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "[ -f /home/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "8080:8080"
    restart: on-failure
    user: "50000:0"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - g:/cache/zoomcamp/logs:/opt/airflow/logs
